# Generated by Django 5.2.3 on 2025-07-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('CHIEF', 'Начальник автоколонны'), ('LOGISTICIAN', 'Специалист логистики'), ('ACCOUNTANT', 'Специалист учета')], default='ACCOUNTANT', max_length=20),
        ),
    ]
